export const mockData = {
    Root: null,
    Documents: [
      {
        OcrData: null,
        IsLocked: false,
        IsTemplateEdit: false,
        IsShortcut: false,
        IsStarred: false,
        IseSign: false,
        HasDetail: false,
        Links: [],
        Versions: [],
        DFXVersions: [],
        Relationships: [],
        IsDFXEdit: false,
        IsFileCheckout: false,
        IsUnderVersionControl: false,
        DownloadFilePath: "\\\\APDFX115P01\\Workfolder\\DFXUser01TEST (5).docx",
        Tags: [],
        IsCheckout: false,
        FileName: "TEST (5).docx",
        ID: "68",
        Fields: [],
        MIME: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        Extension: "docx",
        CreationDateTime: "2025-02-21T00:26:28-08:00",
        LastModifiedDateTime: "2025-01-22T23:14:20-08:00",
        CreatedBy: "KONTOSO\\dfxuser01",
        LastModifiedBy: "",
        CheckedOutBy: "",
        CheckedOutByName2: null,
        CheckedOutBySid2: null,
        CheckedSid: null,
        Name: "TEST (5).docx",
        Template: null,
        TemplateName: "",
        URL: "https://DEMO.datafabricx.com/laserfiche/DocView.aspx?db=LFRepo&docid=68",
        FolderPath: null,
        Repository: null,
        RepoName: "LFRepo",
        Bytes: null,
        Owner: null,
        AlreadyCheckout: false,
        Volume: null,
        VolumeId: 0,
        PageCount: 0,
        CurrentVersion: 0,
        Count: {
          PageCount: 0,
          ImageCount: 0,
          ImageSize: 0,
          TextCount: 0,
          TextSize: 0,
          ElectronicFileSize: 0,
          WordLocationSize: 0,
          ThumbnailSize: 0,
          AnnotationCount: 0,
          AnnotationSize: 0,
          TotalSize: 0,
        },
        OcrText: null,
        HasOcr: false,
        HasAttachment: false,
        AdditionalFields: [],
        HasClassification: null,
        ClassficationText: null,
        ClassificationStatus: null,
        FileModifiedDate: "2025-01-22T23:14:20.677-08:00",
        FileCreationDateTime: "2025-02-21T00:26:28-08:00",
        LocalFile: null,
      },
      {
        OcrData: null,
        IsLocked: false,
        IsTemplateEdit: false,
        IsShortcut: false,
        IsStarred: false,
        IseSign: false,
        HasDetail: false,
        Links: [],
        Versions: [],
        DFXVersions: [],
        Relationships: [],
        IsDFXEdit: false,
        IsFileCheckout: false,
        IsUnderVersionControl: false,
        DownloadFilePath: "\\\\APDFX115P01\\Workfolder\\DFXUser01TEST (8).docx",
        Tags: [],
        IsCheckout: false,
        FileName: "TEST (8).docx",
        ID: "62",
        Fields: [],
        MIME: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        Extension: "docx",
        CreationDateTime: "2025-02-01T12:16:52-08:00",
        LastModifiedDateTime: "2025-02-01T12:17:28-08:00",
        CreatedBy: "KONTOSO\\dfxuser01",
        LastModifiedBy: "KONTOSO\\dfxuser01",
        CheckedOutBy: "",
        CheckedOutByName2: null,
        CheckedOutBySid2: null,
        CheckedSid: null,
        Name: "TEST (8).docx",
        Template: null,
        TemplateName: "",
        URL: "https://DEMO.datafabricx.com/laserfiche/DocView.aspx?db=LFRepo&docid=62",
        FolderPath: null,
        Repository: null,
        RepoName: "LFRepo",
        Bytes: null,
        Owner: null,
        AlreadyCheckout: false,
        Volume: null,
        VolumeId: 0,
        PageCount: 0,
        CurrentVersion: 0,
        Count: {
          PageCount: 0,
          ImageCount: 0,
          ImageSize: 0,
          TextCount: 0,
          TextSize: 0,
          ElectronicFileSize: 0,
          WordLocationSize: 0,
          ThumbnailSize: 0,
          AnnotationCount: 0,
          AnnotationSize: 0,
          TotalSize: 0,
        },
        OcrText: null,
        HasOcr: false,
        HasAttachment: false,
        AdditionalFields: [],
        HasClassification: null,
        ClassficationText: null,
        ClassificationStatus: null,
        FileModifiedDate: "2025-01-22T23:14:20.677-08:00",
        FileCreationDateTime: "2025-02-01T12:16:52-08:00",
        LocalFile: null,
      },
      {
        OcrData: null,
        IsLocked: false,
        IsTemplateEdit: false,
        IsShortcut: false,
        IsStarred: false,
        IseSign: false,
        HasDetail: false,
        Links: [],
        Versions: [],
        DFXVersions: [],
        Relationships: [],
        IsDFXEdit: false,
        IsFileCheckout: false,
        IsUnderVersionControl: false,
        DownloadFilePath: "\\\\APDFX115P01\\Workfolder\\DFXUser01TEST (7).docx",
        Tags: [],
        IsCheckout: false,
        FileName: "TEST (7).docx",
        ID: "60",
        Fields: [],
        MIME: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        Extension: "docx",
        CreationDateTime: "2025-02-01T12:16:52-08:00",
        LastModifiedDateTime: "2025-02-01T12:17:43-08:00",
        CreatedBy: "KONTOSO\\dfxuser01",
        LastModifiedBy: "KONTOSO\\dfxuser01",
        CheckedOutBy: "",
        CheckedOutByName2: null,
        CheckedOutBySid2: null,
        CheckedSid: null,
        Name: "TEST (7).docx",
        Template: null,
        TemplateName: "",
        URL: "https://DEMO.datafabricx.com/laserfiche/DocView.aspx?db=LFRepo&docid=60",
        FolderPath: null,
        Repository: null,
        RepoName: "LFRepo",
        Bytes: null,
        Owner: null,
        AlreadyCheckout: false,
        Volume: null,
        VolumeId: 0,
        PageCount: 0,
        CurrentVersion: 0,
        Count: {
          PageCount: 0,
          ImageCount: 0,
          ImageSize: 0,
          TextCount: 0,
          TextSize: 0,
          ElectronicFileSize: 0,
          WordLocationSize: 0,
          ThumbnailSize: 0,
          AnnotationCount: 0,
          AnnotationSize: 0,
          TotalSize: 0,
        },
        OcrText: null,
        HasOcr: false,
        HasAttachment: false,
        AdditionalFields: [],
        HasClassification: null,
        ClassficationText: null,
        ClassificationStatus: null,
        FileModifiedDate: "2025-01-22T23:14:20.677-08:00",
        FileCreationDateTime: "2025-02-01T12:16:52-08:00",
        LocalFile: null,
      },
    ],
    DeletedDocuments: [],
    MaxCount: 3,
    GroupData: null,
    QueryString: "((({LF:ID=60} | {LF:ID=62} | {LF:ID=68})))",
    Repository: null,
    AllData: null,
    User: null,
    Status: "Success",
    ErrorMessage: null,
    DataID: 0,
    ResultID: [],
    DataPath: null,
    Data: null,
    DataCount: 0,
    Name: null,
  }

export const TabsData = [
  { id: 1, label: "Metadata" },
  { id: 2, label: "Preview" },
  { id: 3, label: "Chat" },
];
